name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
    - type: textarea
    id: what-happened
    attributes:
        label: What happened?
        description: And, what did you expect to happen?
    validations:
        required: true
    - type: textarea
    attributes:
        label: Anything else?
        description: |
        Images? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
        required: false
    - type: checkboxes
    id: exists
    attributes:
        label: Is there an existing issue for this?
        description: Please [search here](https://github.com/pico-fbw/pico-fbw.org/issues) to see if an issue has already been made.
        options:
        - label: I have searched for existing issues before opening this issue.
        required: true
    - type: markdown
    attributes:
        value: |
            Thanks for taking the time to fill out this bug report!
            Please note that we may ask for additional information to clarify and fix your bug, so please keep watch on this issue thread.
